export { default as HeaderLogo } from './components/HeaderLogo/HeaderLogo.svg'
export { default as BrandWatermark } from './components/BrandWatermark/BrandWatermark.svg'
export { default as BackgroundChange } from './components/FormatPage/BackgroundChange.svg'
export { default as MinusText } from './components/FormatPage/MinusText.svg'
export { default as PlusText } from './components/FormatPage/PlusText.svg'
export { default as AlertSuccessIcon } from './icons/AlertSuccessIcon.svg'
export { default as AlertErrorIcon } from './icons/AlertErrorIcon.svg'
export { default as AlertWarningIcon } from './icons/AlertWarningIcon.svg'
export { default as AlertInfoIcon } from './icons/AlertInfoIcon.svg'
export { default as AlertCloseIcon } from './icons/AlertCloseIcon.svg'
export { default as DocSignIcon } from './icons/DocSignIcon.svg'
export { default as DocSignedIcon } from './icons/DocSignedIcon.svg'
export { default as DocDigitalIcon } from './icons/DocDigitalIcon.svg'
export { default as Vector } from './icons/Vector.svg'
export { default as LogoClaveUnicaIcon } from './icons/LogoClaveUnicaIcon.svg'
export { default as Reload } from './icons/Reload.svg'
export { default as ArrowForward } from './icons/ArrowForward.svg'
export { default as CompareArrowsIcon } from './icons/CompareArrowsIcon.svg'
export { default as PencilWrite } from './icons/PencilWriteIcon.svg'
export { default as PencilSign } from './icons/PencilSignIcon.svg'
export { default as VisarIcon } from './icons/VisarIcon.svg'
export { default as CsvDown } from './icons/CsvDownIcon.svg'
export { default as Pending } from './icons/Pending.svg'
export { default as Done } from './icons/Done.svg'
export { default as CcPlusIcon } from './icons/CcPlusIcon.svg'
<<<<<<< HEAD
export { default as ZoomIcon } from './icons/ZoomIcon.svg'
=======
export { default as CsvExport } from './icons/CsvExport.svg'
>>>>>>> develop_issues
